name: Scrape Talk Locations

on:
  workflow_dispatch:
  push:
    paths:
      - '_talks/**'
      - 'talkmap.ipynb'
      - '.github/workflows/scrape_talks.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install jupyter ipykernel pandas requests beautifulsoup4 geopy  # Add other dependencies as needed
        pip install getorg --upgrade
        python -m ipykernel install --user --name python3 --display-name "Python 3"

    - name: Run Jupyter Notebook
      working-directory: _talks
      run: |
        jupyter nbconvert --to notebook --execute ../talkmap.ipynb --output talkmap_out.ipynb --output-dir .. --ExecutePreprocessor.kernel_name=python3

    - name: Commit changes
      run: |
        git config user.name "HONGRUI WU"
        git config user.email "109461556+oneHFR@users.noreply.github.com"
        git add talkmap talkmap_out.ipynb
        git commit -m "Automated update of talk locations" || echo "No changes to commit"
        git push
